### ISSUE TITLE
GCP is broken in Spinnaker 1.33.0

### ISSUE THREAD

**Issue by ashleykleynhans** [spinnaker/spinnaker#6939]
### Issue Summary:

GCP is broken in Spinnaker 1.33.0

### Cloud Provider(s):

* aws
* gcp

### Environment:

* Ubuntu 22.04 LTS
* Spinnaker 1.33.0

### Feature Area:

Clouddriver?

#### Expected behavior:

The GCP clusters should load and be displayed.

#### Actual behavior:

The GCP clusters are not able to load in Spinnaker 1.33.0 (they work fine in 1.32.4).

### Steps to Reproduce:

1. Upgrade Spinnaker to version 1.33.0.
2. Click on a GCP Application.
3. Observe that the GCP clusters cannot load.

### Additional Details:

The following screenshot shows what I am observing
<img width="931" alt="Screenshot 2024-04-02 at 11 41 59" src="https://github.com/spinnaker/spinnaker/assets/886709/d6cc39a3-f481-4738-b5f4-b083dd34210f">
This works fine in Spinnaker 1.32.4, but does not work in Spinnaker 1.33.0.

**Comment by dbyron-sf** [comment]
Anything interesting in the clouddriver logs (or elsewhere I suppose, but I'd look there first)?

**Comment by ashleykleynhans** [comment]
I am struggling to find the exact cause of the issue but this is constantly appearing in the Clouddriver logs:
```
Caused by: java.lang.NoSuchMethodError: 'java.util.Map java.util.Map.withDefault(groovy.lang.Closure)'
	at com.netflix.spinnaker.clouddriver.google.model.GoogleApplication$View.<init>(GoogleApplication.groovy:41) ~[clouddriver-google-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.google.model.GoogleApplication.getView(GoogleApplication.groovy:30) ~[clouddriver-google-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleApplicationProvider.applicationFromCacheData(GoogleApplicationProvider.java:120) ~[clouddriver-google-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleApplicationProvider.applicationFromCacheData(GoogleApplicationProvider.java:105) ~[clouddriver-google-5.83.0.jar:5.83.0]
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[na:na]
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1693) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[na:na]
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[na:na]
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[na:na]
	at com.netflix.spinnaker.clouddriver.google.provider.view.GoogleApplicationProvider.getApplications(GoogleApplicationProvider.java:69) ~[clouddriver-google-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.model.ApplicationProvider$getApplications.call(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-3.0.17.jar:3.0.17]
	at com.netflix.spinnaker.clouddriver.model.ApplicationProvider$getApplications.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.controllers.ApplicationsController$_list_closure1$_closure6.doCall(ApplicationsController.groovy:59) ~[clouddriver-web-5.83.0.jar:5.83.0]
	at jdk.internal.reflect.GeneratedMethodAccessor1103.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.Closure.call(Closure.java:428) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectMany(DefaultGroovyMethods.java:3984) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectMany(DefaultGroovyMethods.java:3876) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.collectMany(DefaultGroovyMethods.java:3852) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.dgm$124.invoke(Unknown Source) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:242) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:51) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139) ~[groovy-3.0.17.jar:3.0.17]
	at com.netflix.spinnaker.clouddriver.controllers.ApplicationsController$_list_closure1.doCall(ApplicationsController.groovy:59) ~[clouddriver-web-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.controllers.ApplicationsController$_list_closure1.doCall(ApplicationsController.groovy) ~[clouddriver-web-5.83.0.jar:5.83.0]
	at jdk.internal.reflect.GeneratedMethodAccessor1392.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-3.0.17.jar:3.0.17]
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.Closure.call(Closure.java:412) ~[groovy-3.0.17.jar:3.0.17]
	at groovy.lang.Closure.call(Closure.java:406) ~[groovy-3.0.17.jar:3.0.17]
	at com.netflix.spinnaker.clouddriver.requestqueue.RequestQueue$NOOP.execute(RequestQueue.java:97) ~[clouddriver-core-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.requestqueue.RequestQueue.execute(RequestQueue.java:80) ~[clouddriver-core-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.requestqueue.RequestQueue$execute.call(Unknown Source) ~[na:na]
	at com.netflix.spinnaker.clouddriver.controllers.ApplicationsController.list(ApplicationsController.groovy:58) ~[clouddriver-web-5.83.0.jar:5.83.0]
	at com.netflix.spinnaker.clouddriver.controllers.ApplicationsController$$FastClassBySpringCGLIB$$215633db.invoke(<generated>) ~[clouddriver-web-5.83.0.jar:5.83.0]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:793) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:61) ~[spring-security-core-5.5.8.jar:5.5.8]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763) ~[spring-aop-5.3.27.jar:5.3.27]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708) ~[spring-aop-5.3.27.jar:5.3.27]
	at com.netflix.spinnaker.clouddriver.controllers.ApplicationsController$$EnhancerBySpringCGLIB$$71883890.list(<generated>) ~[clouddriver-web-5.83.0.jar:5.83.0]
	at jdk.internal.reflect.GeneratedMethodAccessor1391.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150) ~[spring-web-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.3.27.jar:5.3.27]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1072) ~[spring-webmvc-5.3.27.jar:5.3.27]
	... 68 common frames omitted
```

**Comment by j-sandy** [comment]
I tried to reproduce this issue, but failed to do so. @ashleykleynhans could you please try to clean the redis and then try to reproduce it ? And if you can provide few more specific steps, it would help to reproduce the issue.

**Comment by ashleykleynhans** [comment]
I don't want to do anything with Redis because this is my production Spinnaker application and I can't afford for it to get broken.

**Comment by dbyron-sf** [comment]
It could be that certain info in redis triggers the bug.

If the info @j-sandy is asking to clean is info that caching agents store, then it could be OK to (carefully) remove it even from a prod instance, since the agents would regenerate it on the next run.  Is that what you're asking @j-sandy ?

**Comment by j-sandy** [comment]
> It could be that certain info in redis triggers the bug.
> 
> If the info @j-sandy is asking to clean is info that caching agents store, then it could be OK to (carefully) remove it even from a prod instance, since the agents would regenerate it on the next run. Is that what you're asking @j-sandy ?

Yes, I mean the same.

**Comment by ashleykleynhans** [comment]
Can you advise what data needs to be removed?  I am not familiar with what gets stored in Redis and don't know what can be removed to test this.

**Comment by dbyron-sf** [comment]
I bet something similar to https://github.com/spinnaker/clouddriver/pull/6040 would fix this, though it may take slightly more to handle [withDefault](https://github.com/spinnaker/clouddriver/blob/2ac17cf70cd6ae5bf740c3ce63ddc1682ba0c2f1/clouddriver-google/src/main/groovy/com/netflix/spinnaker/clouddriver/google/model/GoogleApplication.groovy#L41).

**Comment by ashleykleynhans** [comment]
This is fixed in Spinnaker 1.34.0.

**Comment by ashleykleynhans** [comment]
Also fixed in Spinnaker 1.33.1.
