### ISSUE TITLE
Failed to start igor

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#6623]
### Issue Summary:
It failed to start igor and threw below error message after deployed successfully. After investigated, it seems that the failure is caused by the commit https://github.com/spinnaker/igor/pull/997. @j-sandy , Could you help to have a look and fix it asap since we're blocked now? Thanks.

### Error Message:
```
2022-03-14 09:23:54.486  WARN 27038 --- [   scheduling-5] c.n.s.igor.plugins.PluginsBuildMonitor   : ****LOCKING NOT ENABLED***, not recommend
ed running on more than one node.
2022-03-14 09:23:54.488  INFO 27038 --- [   scheduling-5] c.n.s.i.plugins.front50.Front50Service   : ---> HTTP GET http://localhost:8080/plugi
nInfo
2022-03-14 09:23:54.495  INFO 27038 --- [   scheduling-5] c.n.s.i.plugins.front50.Front50Service   : ---- ERROR http://localhost:8080/pluginIn
fo
2022-03-14 09:23:54.495  INFO 27038 --- [   scheduling-5] c.n.s.i.plugins.front50.Front50Service   : java.lang.NoSuchMethodError: 'void brave.
http.HttpClientHandler.handleReceive(brave.http.HttpClientResponse, brave.Span)'
at brave.okhttp3.TracingInterceptor.intercept(TracingInterceptor.java:81)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:74)
at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
at okhttp3.RealCall.execute(RealCall.java:81)
at com.jakewharton.retrofit.Ok3Client.execute(Ok3Client.java:41)
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
at com.sun.proxy.$Proxy135.listPluginInfo(Unknown Source)
at com.netflix.spinnaker.igor.plugins.front50.PluginReleaseService.lambda$getPluginReleases$4(PluginReleaseService.java:69)
at com.netflix.spinnaker.security.AuthenticatedRequest.allowAnonymous(AuthenticatedRequest.java:137)
at com.netflix.spinnaker.igor.plugins.front50.PluginReleaseService.getPluginReleases(PluginReleaseService.java:67)
at com.netflix.spinnaker.igor.plugins.front50.PluginReleaseService.getPluginReleasesSinceTimestamps(PluginReleaseService.java:41)
at com.netflix.spinnaker.igor.plugins.PluginsBuildMonitor.generateDelta(PluginsBuildMonitor.java:74)
at com.netflix.spinnaker.igor.plugins.PluginsBuildMonitor.generateDelta(PluginsBuildMonitor.java:41)
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.internalPollSingle(CommonPollingMonitor.java:169)
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.pollSingle(CommonPollingMonitor.java:144)
at com.netflix.spinnaker.igor.plugins.PluginsBuildMonitor.poll(PluginsBuildMonitor.java:122)
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.lambda$onApplicationEvent$0(CommonPollingMonitor.java:94)
at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160)
at com.netflix.spectator.micrometer.MicrometerTimer.record(MicrometerTimer.java:47)
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.lambda$onApplicationEvent$1(CommonPollingMonitor.java:91)
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

2022-03-14 09:23:54.495  INFO 27038 --- [   scheduling-5] c.n.s.i.plugins.front50.Front50Service   : ---- END ERROR
2022-03-14 09:23:54.495 ERROR 27038 --- [   scheduling-5] c.n.s.igor.plugins.PluginsBuildMonitor   : Failed to update monitor items for monito
r=PluginsBuildMonitor:partition=front50

retrofit.RetrofitError: 'void brave.http.HttpClientHandler.handleReceive(brave.http.HttpClientResponse, brave.Span)'
at retrofit.RetrofitError.unexpectedError(RetrofitError.java:44) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400) ~[retrofit-1.9.0.jar:na]
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240) ~[retrofit-1.9.0.jar:na]
at com.sun.proxy.$Proxy135.listPluginInfo(Unknown Source) ~[na:na]
at com.netflix.spinnaker.igor.plugins.front50.PluginReleaseService.lambda$getPluginReleases$4(PluginReleaseService.java:69) ~[igor-mon
itor-plugins.jar:na]
at com.netflix.spinnaker.security.AuthenticatedRequest.allowAnonymous(AuthenticatedRequest.java:137) ~[kork-security-7.132.0.jar:7.132
.0]
at com.netflix.spinnaker.igor.plugins.front50.PluginReleaseService.getPluginReleases(PluginReleaseService.java:67) ~[igor-monitor-plug
ins.jar:na]
at com.netflix.spinnaker.igor.plugins.front50.PluginReleaseService.getPluginReleasesSinceTimestamps(PluginReleaseService.java:41) ~[ig
or-monitor-plugins.jar:na]
at com.netflix.spinnaker.igor.plugins.PluginsBuildMonitor.generateDelta(PluginsBuildMonitor.java:74) ~[igor-monitor-plugins.jar:na]
at com.netflix.spinnaker.igor.plugins.PluginsBuildMonitor.generateDelta(PluginsBuildMonitor.java:41) ~[igor-monitor-plugins.jar:na]
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.internalPollSingle(CommonPollingMonitor.java:169) ~[igor-core.jar:na]
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.pollSingle(CommonPollingMonitor.java:144) ~[igor-core.jar:na]
at com.netflix.spinnaker.igor.plugins.PluginsBuildMonitor.poll(PluginsBuildMonitor.java:122) ~[igor-monitor-plugins.jar:na]
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.lambda$onApplicationEvent$0(CommonPollingMonitor.java:94) ~[igor-core.jar:n
a]
at io.micrometer.core.instrument.AbstractTimer.record(AbstractTimer.java:160) ~[micrometer-core-1.3.16.jar:1.3.16]
at com.netflix.spectator.micrometer.MicrometerTimer.record(MicrometerTimer.java:47) ~[spectator-reg-micrometer-1.0.6.jar:1.0.6]
at com.netflix.spinnaker.igor.polling.CommonPollingMonitor.lambda$onApplicationEvent$1(CommonPollingMonitor.java:91) ~[igor-core.jar:n
a]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-contex
t-5.2.12.RELEASE.jar:5.2.12.RELEASE]
at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) ~[spring-context-5.2.12.RELEASE.ja
r:5.2.12.RELEASE]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.NoSuchMethodError: 'void brave.http.HttpClientHandler.handleReceive(brave.http.HttpClientResponse, brave.Span)'
at brave.okhttp3.TracingInterceptor.intercept(TracingInterceptor.java:81) ~[brave-instrumentation-okhttp3-5.12.3.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:74) ~[kork-web-7.132.0.jar:7.132.0]
at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:36) ~[kork-web-7.132.0.jar:7.132.0]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar:na]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar:na]
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar:na]
at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar:na]
at com.jakewharton.retrofit.Ok3Client.execute(Ok3Client.java:41) ~[retrofit1-okhttp3-client-1.1.0.jar:na]
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326) ~[retrofit-1.9.0.jar:na]
... 23 common frames omitted
```

### Cloud Provider(s):
Azure

### Environment:
ubuntu 16.04

### Feature Area:
Igor

### Steps to Reproduce:
1. hal config version edit --version branch:upstream/master
2. hal deploy apply
3. It failed to start Igor.

**Comment by j-sandy** [comment]
Below is dependency insight without enforcedPlatform clause:
```
$ ./gradlew igor-web:dI --dependency io.zipkin.brave --configuration runtimeClasspath

> Task :igor-web:dependencyInsight
io.zipkin.brave:brave:5.12.3
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]
   Selection reasons:
      - By constraint
      - By conflict resolution : between versions 5.12.3 and 5.10.1

io.zipkin.brave:brave:5.12.3
+--- io.zipkin.brave:brave-instrumentation-http:5.12.3
|    +--- io.spinnaker.kork:kork-bom:7.132.0 (requested io.zipkin.brave:brave-instrumentation-http:5.10.1)
|    |    +--- runtimeClasspath
|    |    +--- project :igor-monitor-artifactory
|    |    |    \--- runtimeClasspath
|    |    +--- project :igor-monitor-plugins
|    |    |    \--- runtimeClasspath
|    |    +--- project :igor-monitor-travis
|    |    |    \--- runtimeClasspath
|    |    \--- project :igor-core
|    |         +--- runtimeClasspath
|    |         +--- project :igor-monitor-artifactory (*)
|    |         +--- project :igor-monitor-plugins (*)
|    |         \--- project :igor-monitor-travis (*)
|    \--- io.zipkin.brave:brave-instrumentation-okhttp3:5.12.3
|         +--- io.spinnaker.kork:kork-bom:7.132.0 (*)
|         +--- io.spinnaker.kork:kork-retrofit:7.132.0
|         |    +--- io.spinnaker.kork:kork-bom:7.132.0 (*)
|         |    \--- io.spinnaker.kork:kork-runtime:7.132.0
|         |         +--- runtimeClasspath (requested io.spinnaker.kork:kork-runtime)
|         |         \--- io.spinnaker.kork:kork-bom:7.132.0 (*)
|         \--- io.spinnaker.kork:kork-web:7.132.0
|              +--- runtimeClasspath (requested io.spinnaker.kork:kork-web)
|              +--- project :igor-monitor-travis (requested io.spinnaker.kork:kork-web) (*)
|              +--- io.spinnaker.kork:kork-bom:7.132.0 (*)
|              +--- io.spinnaker.kork:kork-plugins:7.132.0
|              |    +--- runtimeClasspath (requested io.spinnaker.kork:kork-plugins)
|              |    \--- io.spinnaker.kork:kork-bom:7.132.0 (*)
|              +--- io.spinnaker.fiat:fiat-api:1.30.0
|              |    \--- runtimeClasspath
|              +--- io.spinnaker.kork:kork-runtime:7.132.0 (*)
|              \--- io.spinnaker.kork:kork-retrofit:7.132.0 (*)
\--- io.zipkin.brave:brave-instrumentation-okhttp3:5.12.3 (*)

io.zipkin.brave:brave:5.10.1 -> 5.12.3
\--- io.spinnaker.kork:kork-bom:7.132.0
     +--- runtimeClasspath
     +--- project :igor-monitor-artifactory
     |    \--- runtimeClasspath
     +--- project :igor-monitor-plugins
     |    \--- runtimeClasspath
     +--- project :igor-monitor-travis
     |    \--- runtimeClasspath
     \--- project :igor-core
          +--- runtimeClasspath
          +--- project :igor-monitor-artifactory (*)
          +--- project :igor-monitor-plugins (*)
          \--- project :igor-monitor-travis (*)

io.zipkin.brave:brave-instrumentation-http:5.12.3
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]
   Selection reasons:
      - By constraint
      - By conflict resolution : between versions 5.12.3 and 5.10.1

io.zipkin.brave:brave-instrumentation-http:5.12.3
\--- io.zipkin.brave:brave-instrumentation-okhttp3:5.12.3
     +--- io.spinnaker.kork:kork-bom:7.132.0
     |    +--- runtimeClasspath
     |    +--- project :igor-monitor-artifactory
     |    |    \--- runtimeClasspath
     |    +--- project :igor-monitor-plugins
     |    |    \--- runtimeClasspath
     |    +--- project :igor-monitor-travis
     |    |    \--- runtimeClasspath
     |    \--- project :igor-core
     |         +--- runtimeClasspath
     |         +--- project :igor-monitor-artifactory (*)
     |         +--- project :igor-monitor-plugins (*)
     |         \--- project :igor-monitor-travis (*)
     +--- io.spinnaker.kork:kork-retrofit:7.132.0
     |    +--- io.spinnaker.kork:kork-bom:7.132.0 (*)
     |    \--- io.spinnaker.kork:kork-runtime:7.132.0
     |         +--- runtimeClasspath (requested io.spinnaker.kork:kork-runtime)
     |         \--- io.spinnaker.kork:kork-bom:7.132.0 (*)
     \--- io.spinnaker.kork:kork-web:7.132.0
          +--- runtimeClasspath (requested io.spinnaker.kork:kork-web)
          +--- project :igor-monitor-travis (requested io.spinnaker.kork:kork-web) (*)
          +--- io.spinnaker.kork:kork-bom:7.132.0 (*)
          +--- io.spinnaker.kork:kork-plugins:7.132.0
          |    +--- runtimeClasspath (requested io.spinnaker.kork:kork-plugins)
          |    \--- io.spinnaker.kork:kork-bom:7.132.0 (*)
          +--- io.spinnaker.fiat:fiat-api:1.30.0
          |    \--- runtimeClasspath
          +--- io.spinnaker.kork:kork-runtime:7.132.0 (*)
          \--- io.spinnaker.kork:kork-retrofit:7.132.0 (*)

io.zipkin.brave:brave-instrumentation-http:5.10.1 -> 5.12.3
\--- io.spinnaker.kork:kork-bom:7.132.0
     +--- runtimeClasspath
     +--- project :igor-monitor-artifactory
     |    \--- runtimeClasspath
     +--- project :igor-monitor-plugins
     |    \--- runtimeClasspath
     +--- project :igor-monitor-travis
     |    \--- runtimeClasspath
     \--- project :igor-core
          +--- runtimeClasspath
          +--- project :igor-monitor-artifactory (*)
          +--- project :igor-monitor-plugins (*)
          \--- project :igor-monitor-travis (*)

io.zipkin.brave:brave-instrumentation-okhttp3:5.12.3 (by constraint)
   variant "runtime" [
      org.gradle.status              = release (not requested)
      org.gradle.usage               = java-runtime
      org.gradle.libraryelements     = jar
      org.gradle.category            = library

      Requested attributes not found in the selected variant:
         org.gradle.dependency.bundling = external
         org.gradle.jvm.version         = 11
   ]

io.zipkin.brave:brave-instrumentation-okhttp3:5.12.3
+--- io.spinnaker.kork:kork-bom:7.132.0
|    +--- runtimeClasspath
|    +--- project :igor-monitor-artifactory
|    |    \--- runtimeClasspath
|    +--- project :igor-monitor-plugins
|    |    \--- runtimeClasspath
|    +--- project :igor-monitor-travis
|    |    \--- runtimeClasspath
|    \--- project :igor-core
|         +--- runtimeClasspath
|         +--- project :igor-monitor-artifactory (*)
|         +--- project :igor-monitor-plugins (*)
|         \--- project :igor-monitor-travis (*)
+--- io.spinnaker.kork:kork-retrofit:7.132.0
|    +--- io.spinnaker.kork:kork-bom:7.132.0 (*)
|    \--- io.spinnaker.kork:kork-runtime:7.132.0
|         +--- runtimeClasspath (requested io.spinnaker.kork:kork-runtime)
|         \--- io.spinnaker.kork:kork-bom:7.132.0 (*)
\--- io.spinnaker.kork:kork-web:7.132.0
     +--- runtimeClasspath (requested io.spinnaker.kork:kork-web)
     +--- project :igor-monitor-travis (requested io.spinnaker.kork:kork-web) (*)
     +--- io.spinnaker.kork:kork-bom:7.132.0 (*)
     +--- io.spinnaker.kork:kork-plugins:7.132.0
     |    +--- runtimeClasspath (requested io.spinnaker.kork:kork-plugins)
     |    \--- io.spinnaker.kork:kork-bom:7.132.0 (*)
     +--- io.spinnaker.fiat:fiat-api:1.30.0
     |    \--- runtimeClasspath
     +--- io.spinnaker.kork:kork-runtime:7.132.0 (*)
     \--- io.spinnaker.kork:kork-retrofit:7.132.0 (*)
```

**Comment by neil-yechenwei** [comment]
@j-sandy ，thanks for investigation. Could you fix these issues asap since we are blocked now? Thanks in advance.

**Comment by j-sandy** [comment]
@neil-yechenwei Issue is fixed. Could you please verify and close the issue ? Thanks

**Comment by neil-yechenwei** [comment]
Sure. Thanks. I will verify it.

**Comment by neil-yechenwei** [comment]
Seems this component can start successfully. So closed this issue.
