### ISSUE TITLE
Failed to start echo

### ISSUE THREAD

**Issue by neil-yechenwei** [spinnaker/spinnaker#6624]
### Issue Summary:
It failed to start echo and threw below error message after deployed successfully. After investigated, it seems that the failure is caused by the commit https://github.com/spinnaker/echo/pull/1158. @j-sandy , Could you help to have a look and fix it asap since we're blocked now? Thanks.

### Error Message:
```
2022-03-14 09:35:10.379  INFO 21000 --- [eduler_Worker-4] c.n.s.e.s.a.p.PipelineConfigsPollingJob  : Running the pipeline configs polling agen
t...
2022-03-14 09:35:33.150  INFO 21000 --- [pool-1-thread-1] c.n.s.echo.services.Front50Service       : ---> HTTP GET http://localhost:8080/pipel
ines?restricted=false
2022-03-14 09:35:33.159  INFO 21000 --- [pool-1-thread-1] c.n.s.echo.services.Front50Service       : ---- ERROR http://localhost:8080/pipeline
s?restricted=false
2022-03-14 09:35:33.159  INFO 21000 --- [pool-1-thread-1] c.n.s.echo.services.Front50Service       : java.lang.NoSuchMethodError: 'void brave.
http.HttpClientHandler.handleReceive(brave.http.HttpClientResponse, brave.Span)'
at brave.okhttp3.TracingInterceptor.intercept(TracingInterceptor.java:81)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at com.netflix.spinnaker.okhttp.MetricsInterceptor.doIntercept(MetricsInterceptor.java:74)
at com.netflix.spinnaker.okhttp.OkHttp3MetricsInterceptor.intercept(OkHttp3MetricsInterceptor.java:36)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
at okhttp3.RealCall.execute(RealCall.java:81)
at com.jakewharton.retrofit.Ok3Client.execute(Ok3Client.java:41)
at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
at com.sun.proxy.$Proxy139.getPipelines(Unknown Source)
at com.netflix.spinnaker.echo.pipelinetriggers.PipelineCache.lambda$fetchRawPipelines$2(PipelineCache.java:191)
at com.netflix.spinnaker.security.AuthenticatedRequest.allowAnonymous(AuthenticatedRequest.java:137)
at com.netflix.spinnaker.echo.pipelinetriggers.PipelineCache.fetchRawPipelines(PipelineCache.java:191)
at com.netflix.spinnaker.echo.pipelinetriggers.PipelineCache.fetchHydratedPipelines(PipelineCache.java:196)
at com.netflix.spinnaker.echo.pipelinetriggers.PipelineCache.pollPipelineConfigs(PipelineCache.java:151)
at com.netflix.spinnaker.echo.pipelinetriggers.PipelineCache$1.run(PipelineCache.java:124)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
```

### Cloud Provider(s):
Azure

### Environment:
ubuntu 16.04

### Feature Area:
Echo

### Steps to Reproduce:
1. hal config version edit --version branch:upstream/master
2. hal deploy apply
3. It failed to start Echo.

**Comment by neil-yechenwei** [comment]
Thanks @dbyron-sf . Seems recently the changes from @j-sandy  also impacts other components like igor (https://github.com/spinnaker/spinnaker/issues/6623). Please also help take a look. Of course, you also can address the problem with below similar steps. Thanks in advance.

1. hal config version edit --version branch:upstream/master
2. hal deploy apply
3. Run this command `netstat -tln | grep 8089` to see if Echo is started successfully.
4. If it's started successfully, run this command `cat ~/dev/spinnaker/logs/echo.log` to see if the error occurs. (Until now, you will see the error message in log)
5. Once the bug fix is ready, then you can goto the folder `~/dev/spinnaker/echo` and check out to the branch that is with the bug fix
6. Run this command `~/dev/spinnaker/scripts/echo-start.sh` to restart this service
7. Run this command `cat ~/dev/spinnaker/logs/echo.log` to see if the error still exists.

**Comment by dbyron-sf** [comment]
These are instructions for seeing the problem...unfortunately not instructions for addressing.  What I was really hoping for were instructions in the form of an additional automated test directly in the echo repo so we could see the problem more easily (i.e. with neither halyard nor a fully running instance of echo).

**Comment by neil-yechenwei** [comment]
Sorry. We don't have that.

**Comment by j-sandy** [comment]
@neil-yechenwei Issue is fixed. Could you please verify and close the issue ? Thanks

**Comment by neil-yechenwei** [comment]
Sure. Thanks. I will verify it.

**Comment by neil-yechenwei** [comment]
Seems this component can start successfully. So closed this issue.
