### ISSUE TITLE
Upgrade to 1.14.x breaks Oracle Provider

### ISSUE THREAD

**Issue by ericsessions** [spinnaker/spinnaker#4488]
### Issue Summary:
When I upgrade to 1.14.x (all versions) from 1.12.7, CloudDriver fails to start up properly.

### Cloud Provider(s):
Oracle Cloud

### Environment:
I have a working 1.12.7 Spinnaker instance running on Kubernetes. When I try to upgrade to 1.14.x using Halyard, CloudDriver never starts up properly. The pod never becomes ready.

### Feature Area (if this issue is UI/UX related, please tag `@spinnaker/ui-ux-team`):
CloudDriver

### Description:
In the CloudDriver logs, I see the following exception and others just like it

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'synchronizeOracleAccounts' defined in class path resource [com/netflix/spinnaker/clouddriver/oracle/security/OracleCredentialsInitializer.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [java.util.List]: Factory method 'synchronizeOracleAccounts' threw exception; nested exception is java.lang.NoClassDefFoundError: org/glassfish/jersey/client/spi/ConnectorProvider
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:627) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:607) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1321) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1160) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:515) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:338) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:209) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.resolveBeanReference(ConfigurationClassEnhancer.java:393) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:366) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.netflix.spinnaker.clouddriver.oracle.security.OracleCredentialsInitializer$$EnhancerBySpringCGLIB$$7d2eda48.synchronizeOracleAccounts(<generated>) ~[clouddriver-oracle.jar:na]
	at com.netflix.spinnaker.clouddriver.oracle.security.OracleCredentialsInitializer$$EnhancerBySpringCGLIB$$7d2eda48$synchronizeOracleAccounts.callCurrent(Unknown Source) ~[na:na]
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) [groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) [groovy-2.5.6.jar:2.5.6]
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:192) [groovy-2.5.6.jar:2.5.6]
	at com.netflix.spinnaker.clouddriver.oracle.security.OracleCredentialsInitializer.oracleNamedAccountCredentials(OracleCredentialsInitializer.groovy:33) ~[clouddriver-oracle.jar:na]
	at com.netflix.spinnaker.clouddriver.oracle.security.OracleCredentialsInitializer$$EnhancerBySpringCGLIB$$7d2eda48.CGLIB$oracleNamedAccountCredentials$4(<generated>) ~[clouddriver-oracle.jar:na]
	at com.netflix.spinnaker.clouddriver.oracle.security.OracleCredentialsInitializer$$EnhancerBySpringCGLIB$$7d2eda48$$FastClassBySpringCGLIB$$12e1d933.invoke(<generated>) ~[clouddriver-oracle.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244) ~[spring-core-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:363) ~[spring-context-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at com.netflix.spinnaker.clouddriver.oracle.security.OracleCredentialsInitializer$$EnhancerBySpringCGLIB$$7d2eda48.oracleNamedAccountCredentials(<generated>) ~[clouddriver-oracle.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	... 84 common frames omitted

### Steps to Reproduce:
Configure Spinnaker 1.14.x to use the Oracle Cloud provider and deploy it.

### Additional Details:

---

**_Please delete the instructions below this line prior to submitting_**

Instructions:

* An issue is not a place to ask questions. Please use [Slack](http://join.spinnaker.io) or [Stack Overflow](http://stackoverflow.com/questions/tagged/spinnaker). 
* Before you open an issue, please [check if a similar issue already exists](https://github.com/spinnaker/spinnaker/issues) or has been closed before.
* Make sure you have read through the [Spinnaker FAQ](https://www.spinnaker.io/community/faqs/) and [Halyard FAQ](https://www.spinnaker.io/setup/quickstart/faq/) to provide as much information as possible.

Descriptions:

* Issue Summary: A brief description of what you're seeing.
* Cloud Provider: AWS, GCP, Kubernetes, Azure, Cloud Foundry, etc. Please assign a label from the right so your issue can be properly sorted.
* Environment: As much information about your Spinnaker environment and configuration that might be relevant to the issue. For example: "I am running Spinnaker using the Amazon images to deploy into AWS and GCP."
* Feature Area: Notifications, Pipelines, UI, Jenkins, etc. Please assign a label from the right so your issue can be properly sorted.
* Description: The behavior you expect to see, and the actual behavior.
* Steps to reproduce: Ideally, an isolated way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem). If not possible, as much information as possible to see this behavior.
* Additional Details: Additional information such as screenshots and exception logs.

**Comment by ezimanyi** [comment]
CC: @shihchang @guoyongzhang

**Comment by spinnakerbot** [comment]
This issue hasn't been updated in 45 days, so we are tagging it as 'stale'. If you want to remove this label, comment:

> @spinnakerbot remove-label stale

**Comment by spinnakerbot** [comment]
This issue is tagged as 'stale' and hasn't been updated  in 45 days, so we are tagging it as 'to-be-closed'. It will be closed in 45 days unless updates are made. If you want to remove this label, comment:

> @spinnakerbot remove-label to-be-closed
